apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app
  namespace: note-app
  labels:
    app: note-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
        - name: noteapp
          image: IMAGE_PLACEHOLDER   # 👈 replaced in pipeline
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-cred